services:
  postgres:
    image: postgres:14
    restart: on-failure
    ports:
      - ${TESTS_POSTGRES_PUBLIC_PORT}:5432
    environment:
      POSTGRES_DB: ${TESTS_POSTGRES_DB}
      POSTGRES_USER: ${TESTS_POSTGRES_USER}
      POSTGRES_PASSWORD: ${TESTS_POSTGRES_PASSWORD}
    healthcheck:
      test: [CMD-SHELL, pg_isready -U postgres]
      interval: 10s
      timeout: 10s
      retries: 3
  minio:
    image: minio/minio:RELEASE.2023-11-15T20-43-25Z
    command: server /data --console-address ":9001"
    restart: on-failure
    ports:
      - ${TESTS_MINIO_PUBLIC_PORT}:9000
      - ${TESTS_MINIO_PUBLIC_PORT_CONSOLE}:9001
    environment:
      MINIO_ROOT_USER: ${TESTS_MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${TESTS_MINIO_ROOT_PASSWORD}
      MINIO_REGION: ${TESTS_MINIO_REGION}
    healthcheck:
      test: [CMD, mc, ready, local]
      interval: 10s
      timeout: 10s
      retries: 3
  rabbit:
    image: rabbitmq:4-management
    restart: on-failure
    ports:
      - ${TESTS_RABBIT_PUBLIC_PORT}:5672
      - ${TESTS_RABBIT_PUBLIC_PORT_MANAGEMENT}:15672
    environment:
      RABBITMQ_DEFAULT_USER: ${TESTS_RABBIT_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${TESTS_RABBIT_DEFAULT_PASS}
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 10s
      retries: 3
