version: "3"

vars:
  COMPOSE_PROJECT_NAME: moderateapi
  TESTS_COMPOSE_PROJECT_NAME: moderateapi_tests
  TESTS_POSTGRES_USER: postgres
  TESTS_POSTGRES_PASSWORD: postgres
  TESTS_POSTGRES_DB: testsmoderateapi
  TESTS_POSTGRES_PUBLIC_PORT: 15432
  TESTS_POSTGRES_URL: postgresql+asyncpg://{{.TESTS_POSTGRES_USER}}:{{.TESTS_POSTGRES_PASSWORD}}@localhost:{{.TESTS_POSTGRES_PUBLIC_PORT}}/{{.TESTS_POSTGRES_DB}}
  TESTS_MINIO_PUBLIC_PORT: 19000
  TESTS_MINIO_PUBLIC_PORT_CONSOLE: 19001
  TESTS_MINIO_ROOT_USER: minio
  TESTS_MINIO_ROOT_PASSWORD: minio123
  TESTS_MINIO_REGION: eu-central-1
  TESTS_MINIO_BUCKET_NAME: moderateapi-tests
  TESTS_MINIO_ENDPOINT_URL: http://localhost:{{.TESTS_MINIO_PUBLIC_PORT}}

env:
  COMPOSE_PROJECT_NAME: "{{.COMPOSE_PROJECT_NAME}}"
  TESTS_POSTGRES_USER: "{{.TESTS_POSTGRES_USER}}"
  TESTS_POSTGRES_PASSWORD: "{{.TESTS_POSTGRES_PASSWORD}}"
  TESTS_POSTGRES_DB: "{{.TESTS_POSTGRES_DB}}"
  TESTS_POSTGRES_PUBLIC_PORT: "{{.TESTS_POSTGRES_PUBLIC_PORT}}"
  TESTS_POSTGRES_URL: "{{.TESTS_POSTGRES_URL}}"
  TESTS_MINIO_PUBLIC_PORT: "{{.TESTS_MINIO_PUBLIC_PORT}}"
  TESTS_MINIO_PUBLIC_PORT_CONSOLE: "{{.TESTS_MINIO_PUBLIC_PORT_CONSOLE}}"
  TESTS_MINIO_ROOT_USER: "{{.TESTS_MINIO_ROOT_USER}}"
  TESTS_MINIO_ROOT_PASSWORD: "{{.TESTS_MINIO_ROOT_PASSWORD}}"
  TESTS_MINIO_REGION: "{{.TESTS_MINIO_REGION}}"
  TESTS_MINIO_BUCKET_NAME: "{{.TESTS_MINIO_BUCKET_NAME}}"
  TESTS_MINIO_ENDPOINT_URL: "{{.TESTS_MINIO_ENDPOINT_URL}}"

dotenv: [.env.dev, .env.dev.default]

tasks:
  dev-up:
    desc: Start the development stack
    cmds:
      - docker compose -f {{.ROOT_DIR}}/docker-compose-dev.yml up -d --build

  dev-down:
    desc: Stop and remove all traces of the development stack
    cmds:
      - docker compose -f {{.ROOT_DIR}}/docker-compose-dev.yml down -v

  test-deps-up:
    desc: Start the services needed for testing
    cmds:
      - >
        docker compose
        -p {{.TESTS_COMPOSE_PROJECT_NAME}}
        -f {{.ROOT_DIR}}/docker-compose-tests.yml
        up -d --build --wait

  test-deps-down:
    desc: Stop the services needed for testing
    cmds:
      - >
        docker compose
        -p {{.TESTS_COMPOSE_PROJECT_NAME}}
        -f {{.ROOT_DIR}}/docker-compose-tests.yml
        down -v

  export-test-env:
    silent: true
    desc: Export the environment variables to run the tests
    cmds:
      - >
        echo "
        export TESTS_POSTGRES_URL={{.TESTS_POSTGRES_URL}} &&
        export TESTS_MINIO_PUBLIC_PORT={{.TESTS_MINIO_PUBLIC_PORT}} &&
        export TESTS_MINIO_PUBLIC_PORT_CONSOLE={{.TESTS_MINIO_PUBLIC_PORT_CONSOLE}} &&
        export TESTS_MINIO_ROOT_USER={{.TESTS_MINIO_ROOT_USER}} &&
        export TESTS_MINIO_ROOT_PASSWORD={{.TESTS_MINIO_ROOT_PASSWORD}} &&
        export TESTS_MINIO_REGION={{.TESTS_MINIO_REGION}} &&
        export TESTS_MINIO_BUCKET_NAME={{.TESTS_MINIO_BUCKET_NAME}} &&
        export TESTS_MINIO_ENDPOINT_URL={{.TESTS_MINIO_ENDPOINT_URL}}"

  test:
    desc: Run the test suite
    cmds:
      - task: test-deps-up
      - poetry run pytest -v
      - task: test-deps-down

  push-minio-image:
    desc: Push a MinIO image tailored for GitHub Actions
    cmds:
      - >
        docker build --platform linux/amd64
        -f {{.ROOT_DIR}}/Dockerfile.minio
        -t {{.ACTIONS_MINIO_IMAGE_LOCAL}}
        {{.ROOT_DIR}}
      - docker tag {{.ACTIONS_MINIO_IMAGE_LOCAL}} {{.ACTIONS_MINIO_IMAGE_REMOTE}}:{{.ACTIONS_MINIO_IMAGE_REMOTE_TAG}}
      - docker push {{.ACTIONS_MINIO_IMAGE_REMOTE}}:{{.ACTIONS_MINIO_IMAGE_REMOTE_TAG}}
