version: "3"

vars:
  COMPOSE_PROJECT_NAME: moderateapi

env:
  COMPOSE_PROJECT_NAME: "{{.COMPOSE_PROJECT_NAME}}"

dotenv: [.env.dev, .env.dev.default]

tasks:
  dev-up:
    desc: Start the development stack
    cmds:
      - docker compose -f {{.ROOT_DIR}}/docker-compose-dev.yml up -d --build --wait

  dev-down:
    desc: Stop and remove all traces of the development stack
    cmds:
      - docker compose -f {{.ROOT_DIR}}/docker-compose-dev.yml down -v
